name: version_lifter
description: A CLI tool to simplify changing Dart and Flutter project versions.
version: 0.1.1
repository: https://github.com/mitryp/version_lifter
issue_tracker: https://github.com/mitryp/version_lifter/issues

environment:
  sdk: ^3.3.3

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  io: ^1.0.4
  path: ^1.9.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.3.0
  xcodeproj: ^0.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  version_lifter:
